### ISSUE TITLE
Text will go beyond margin if it is too long

### ISSUE THREAD

**Issue by liubq7** [jakeryang/resume#2]
Hi, I'm new to latex, the text will go beyond margin if it is too long, and won't line feed automatically. But I don't know how to fix this.

**Comment by jakegut** [comment]
Check out this help page from Overleaf [here](https://www.overleaf.com/learn/latex/line_breaks_and_blank_spaces#Line_breaks).

**Comment by liubq7** [comment]
Thank you for your reply! Just realized I made a stupid mistake 😅

**Comment by iCHAIT** [comment]
@liubq7 How did you solve it? I am trying to do the same and referred to the link above. But neither of `\\`, `\newline` or `\hfill \break` helped.

**Comment by liubq7** [comment]
@iCHAIT Sorry for the late response, guess you already solve that. My understanding is that you can't line feed in the column of tabular (tell me if you find other solution), but the rest part works well.

**Comment by jinensetpal** [comment]
Nested tabular allows multiline entries: https://tex.stackexchange.com/a/40562/226501
