### ISSUE TITLE
Fontawesome external link icon error

### ISSUE THREAD

**Issue by HabibRh26** [jakeryang/resume#3]
![sample](https://user-images.githubusercontent.com/47397271/109304195-18065e80-7866-11eb-8ce2-04b606b0cdce.png)
### I want to add an external link icon in this overleaf template like above. Below is the overleaf snap: <br>
![sample2](https://user-images.githubusercontent.com/47397271/109305008-505a6c80-7867-11eb-80c0-b237a3f4ccf5.png)

### here is the error message that I got: <br>
![error](https://user-images.githubusercontent.com/47397271/109305123-797afd00-7867-11eb-98c7-d6e7133ff64b.png)

## Little brief:
The icon wanted to use is  from font awesome,  [CTAN states](http://mirror.neu.edu.cn/CTAN/fonts/fontawesome/doc/fontawesome.pdf) that: <br>
```The fontawesome package requires the font spec package when using the XƎ(LA)TEXor Lua(LA)TEX engines to load the included otf font. When using the (pdf)(LA)TEXengine, the fontawesome package doesn’t require any external package ```
I used the pdfLatex engine but it still gives error.

**Comment by jakegut** [comment]
It seems like there's a step missing somewhere...

Did you add `\usepackage{fontawesome5}` near the top with the other packages?

**Comment by HabibRh26** [comment]
yes, I did, after you said. <br>

![IMG_20210227_005507](https://user-images.githubusercontent.com/47397271/109343295-50726080-7897-11eb-857b-2ca50d7ebc81.jpg)

**Comment by jakegut** [comment]
According to the documentation, it's `\faExternalLink*` 

You can find all of the icons associated with the fontawesome5 package here: https://latexdraw.com/wp-content/uploads/2021/01/fontawesome5_2.pdf

**Comment by HabibRh26** [comment]
I've also used the same as you mentioned, \faExternalLink right?

**Comment by jakegut** [comment]
Yes, but note the asterisk after `\faExternalLink` so it needs to be `\faExternalLink*`

**Comment by HabibRh26** [comment]
Bang! it works!. aplogy, Thanks, dude.

**Comment by Nitinkumar3399** [comment]
`\faExternalLink*` 
It is correct, it works for me.

**Comment by seeker53** [comment]
@HabibRh26 Can you please provide me this template of your resume
