### ISSUE TITLE
font size change

### ISSUE THREAD

**Issue by HabibRh26** [jakeryang/resume#5]
how do I change font size for the whole document? 
`\documentclass[letterpaper,11pt]{article}` tried changing the 11pt to 14pt nothing happens

**Comment by jakegut** [comment]
The only supported options for that document class are `10pt`, `11pt`, and `12pt` IIRC. 

You can replace that line with `\documentclass[letterpaper,14pt]{extarticle}` which worked for me using `pdfLaTeX`

**Comment by HabibRh26** [comment]
thanks a lot, it worked!
